# Lists for Western, Educated, Industrialized, Rich and Democratic (WEIRD)
# countries
weird_countries = ["United States", "USA", "Canada", "United Kingdom", "UK",
                   "Ireland", "Australia", "New Zealand", "Germany", "France",
                   "Netherlands", "Belgium", "Luxembourg", "Switzerland",
                   "Austria", "Denmark", "Norway", "Sweden", "Finland",
                   "Iceland"]
weird_demonyms = ["American", "Canadian", "British", "Irish", "Australian",
                  "New Zealander", "German", "French", "Dutch", "Belgian",
                  "Luxembourger", "Swiss", "Austrian", "Danish", "Norwegian",
                  "Swedish", "Finnish", "Icelandic"]

# Lists for Latin American and Caribbean (LAC) countries
lac_countries = ["Argentina", "Bolivia", "Brazil", "Chile", "Colombia",
                 "Costa Rica", "Cuba", "Dominican Republic", "Ecuador",
                 "El Salvador", "Guatemala", "Haiti", "Honduras", "Jamaica",
                 "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru",
                 "Puerto Rico", "Uruguay", "Venezuela"]
lac_demonyms = ["Argentinian", "Argentine", "Bolivian", "Brazilian", "Chilean",
                "Colombian", "Costa Rican", "Cuban", "Dominican", "Ecuadorian",
                "Salvadoran", "Salvadorian", "Guatemalan", "Haitian",
                "Honduran", "Jamaican", "Mexican", "Nicaraguan", "Panamanian",
                "Paraguayan", "Peruvian", "Puerto Rican", "Uruguayan",
                "Venezuelan"]

# Lists for all countries
countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola",
             "Antigua and Barbuda", "Argentina", "Armenia", "Australia",
             "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
             "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
             "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
             "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde",
             "Cambodia", "Cameroon", "Canada", "Central African Republic",
             "Chad", "Chile", "China", "Colombia", "Comoros", "Congo",
             "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
             "Czechia", "Denmark", "Djibouti", "Dominica",
             "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
             "Equatorial Guinea", "Eritrea",
             "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
             "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece",
             "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
             "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia",
             "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan",
             "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea",
             "South Korea",
             "Korea",
             "Kosovo", "Kuwait", "Kyrgyzstan", "Laos",
             "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
             "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar",
             "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
             "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
             "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
             "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal",
             "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
             "North Macedonia", "Norway", "Oman", "Pakistan", "Palau",
             "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
             "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
             "Saint Kitts and Nevis", "Saint Lucia",
             "Saint Vincent and the Grenadines", "Samoa", "San Marino",
             "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
             "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
             "Solomon Islands", "Somalia", "South Africa", "South Sudan",
             "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden",
             "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
             "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago",
             "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
             "Ukraine", "United Arab Emirates", "United Kingdom",
             "UK",
             "United States",
             "USA",
             "Uruguay", "Uzbekistan", "Vanuatu",
             "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia",
             "Zimbabwe"]

demonyms = ["Afghan", "Albanian", "Algerian", "Andorran", "Angolan",
            "Antiguan and Barbudan", "Argentinian",
            "Argentine",
            "Armenian", "Australian",
            "Austrian", "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi",
            "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese",
            "Bhutanese", "Bolivian", "Bosnian", "Botswanan", "Brazilian",
            "Bruneian", "Bulgarian", "Burkinabé", "Burundian", "Cabo Verdean",
            "Cambodian", "Cameroonian", "Canadian", "Central African",
            "Chadian", "Chilean", "Chinese", "Colombian", "Comoran",
            "Congolese", "Costa Rican", "Croatian", "Cuban", "Cypriot",
            "Czech", "Danish", "Djiboutian", "Dominican", "Ecuadorean",
            "Egyptian", "Salvadoran",
            "Salvadorian",
            "Equatorial Guinean", "Eritrean",
            "Estonian", "Swazi", "Ethiopian", "Fijian", "Finnish", "French",
            "Gabonese", "Gambian", "Georgian", "German", "Ghanaian", "Greek",
            "Grenadian", "Guatemalan", "Guinean", "Guinea-Bissauan",
            "Guyanese", "Haitian", "Honduran", "Hungarian", "Icelandic",
            "Indian", "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli",
            "Italian", "Jamaican", "Japanese", "Jordanian", "Kazakhstani",
            "Kenyan", "I-Kiribati", "North Korean", "South Korean", "Kosovar",
            "Kuwaiti", "Kyrgyz", "Laotian", "Latvian", "Lebanese", "Mosotho",
            "Liberian", "Libyan", "Liechtensteiner", "Lithuanian",
            "Luxembourger", "Malagasy", "Malawian", "Malaysian", "Maldivian",
            "Malian", "Maltese", "Marshallese", "Mauritanian", "Mauritian",
            "Mexican", "Micronesian", "Moldovan", "Monegasque", "Mongolian",
            "Montenegrin", "Moroccan", "Mozambican", "Burmese", "Namibian",
            "Nauruan", "Nepalese", "Dutch", "New Zealander", "Nicaraguan",
            "Nigerien", "Nigerian", "North Macedonian", "Norwegian", "Omani",
            "Pakistani", "Palauan", "Panamanian", "Papua New Guinean",
            "Paraguayan", "Peruvian", "Filipino", "Polish", "Portuguese",
            "Qatari", "Romanian", "Russian", "Rwandan",
            "Saint Kitts and Nevisian", "Saint Lucian",
            "Saint Vincent and the Grenadines", "Samoan", "San Marinese",
            "Sao Tomean", "Saudi Arabian", "Senegalese", "Serbian",
            "Seychellois", "Sierra Leonean", "Singaporean", "Slovak",
            "Slovenian", "Solomon Islander", "Somali", "South African",
            "South Sudanese", "Spanish", "Sri Lankan", "Sudanese",
            "Surinamese", "Swedish", "Swiss", "Syrian", "Taiwanese", "Tajik",
            "Tanzanian", "Thai", "Timorese", "Togolese", "Tongan",
            "Trinidadian or Tobagonian", "Tunisian", "Turkish", "Turkmen",
            "Tuvaluan", "Ugandan", "Ukrainian", "Emirian", "British",
            "American", "Uruguayan", "Uzbekistani", "Ni-Vanuatu", "Vatican",
            "Venezuelan", "Vietnamese", "Yemenite", "Zambian", "Zimbabwean"]

# Lists for non-WEIRD countries
non_weird_countries = [country for country in countries
                       if country not in weird_countries]
non_weird_demonyms = [demonym for demonym in demonyms
                      if demonym not in weird_demonyms]

# Lists for all countries' names stemmed
stemmed = ["Afghan*", "Alban*", "Alger*", "Andorr*", "Angol*",
           "Antigu* and Barbud*", "Argentin*", "Armen*", "Austral*",
           "Austri*", "Azerbaijan*", "Baham*", "Bahrain*", "Banglades*",
           "Barbad*", "Belarus*", "Belg*", "Beliz*", "Benin*", "Bhutan*",
           "Bolivi*", "Bosnia and Herzegovin*", "Botswan*", "Brazil*",
           "Brune*", "Bulgari*", "Burkina Fas*", "Burund*", "Cabo Verde*",
           "Cambodi*", "Cameroon*", "Canad*", "Central African*", "Chad*",
           "Chil*", "Chin*", "Colomb*", "Comor*", "Cong*", "Costa Ric*",
           "Croat*", "Cub*", "Cypr*", "Czech*", "Denmark*", "Djibout*",
           "Dominic*", "Ecuad*", "Egypt*", "Salvador*",
           "Equatorial Guine*", "Eritre*", "Eston*", "Eswatin*", "Ethiopi*",
           "Fij*", "Finland*", "Franc*", "Gabon*", "Gambi*", "Georg*",
           "German*", "Ghan*", "Greec*", "Grenad*", "Guatemal*", "Guine*",
           "Guinea-Bissau*", "Guyan*", "Hait*", "Hondur*", "Hungar*",
           "Iceland*", "Indi*", "Indones*", "Iran*", "Iraq*", "Irel*",
           "Isra*", "Ital*", "Jamaic*", "Jap*", "Jord*", "Kazakhstan*",
           "Keny*", "Kiribat*", "North Kore*", "South Kore*", "Kosov*",
           "Kuwait*", "Kyrgyzstan*", "Laos*", "Latvi*", "Leban*", "Lesoth*",
           "Liber*", "Liby*", "Liechtenstein*", "Lithuani*", "Luxembourg*",
           "Madagas*", "Malaw*", "Malays*", "Maldiv*", "Mal*", "Malt*",
           "Marshall Islands*", "Mauritani*", "Mauriti*", "Mexic*",
           "Micrones*", "Moldov*", "Monac*", "Mongol*", "Montenegr*",
           "Morocc*", "Mozambiqu*", "Myanm*", "Namibi*", "Naur*", "Nep*",
           "Netherland*", "New Zealand*", "Nicaragu*", "Niger*", "Nigeri*",
           "North Macedonian*", "Norway*", "Oman*", "Pakist*", "Palau*",
           "Panam*", "Papua New Guine*", "Paraguay*", "Per*", "Philippin*",
           "Pol*", "Portug*", "Qatar*", "Romani*", "Russ*", "Rwand*",
           "Saint Kitts and Nevis*", "Saint Luci*",
           "Saint Vincent and the Grenadin*", "Sam*", "San Marin*",
           "Sao Tom* and Principe*", "Saudi Arabi*", "Seneg*", "Serbi*",
           "Seychell*", "Sierra Leon*", "Singapor*", "Slovak*", "Sloven*",
           "Solomon Islands*", "Somal*", "South Afric*", "South Sudan*",
           "Spain*", "Sri Lank*", "Sudan*", "Surinam*", "Swed*",
           "Switzerland*", "Syri*", "Taiw*", "Tajikistan*", "Tanzani*",
           "Thail*", "Timor-Lest*", "Tog*", "Tong*", "Trinidad and Tobag*",
           "Tunisi*", "Turk*", "Turkmenistan*", "Tuvalu*", "Ugand*",
           "Ukrain*", "Emirat*", "Brit*", "Americ*", "Uruguay*",
           "Uzbekistan*", "Vanuat*", "Vatican*", "Venezuel*", "Vietnam*",
           "Yemen*", "Zambi*", "Zimbabw*"]
